# Generated by Django 3.0.3 on 2020-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField('event', 'country_id'),
        migrations.AddField('event', 'country_name', models.CharField(max_length=255, default='Russia'))
    ]
