# Generated by Django 3.0.3 on 2020-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200212_1357'),
    ]

    operations = [
        migrations.AddField('eventuser', 'event_id', models.PositiveIntegerField())
    ]
