# Generated by Django 2.2.10 on 2020-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200212_1358'),
    ]

    operations = [
        migrations.RemoveField('event', 'country_name'),
        migrations.AddField('event', 'latitude', models.DecimalField(
            max_digits=10,
            decimal_places=7,
            default=None, blank=True,
            null=True
        )),
        migrations.AddField('event', 'longitude', models.DecimalField(
            max_digits=10,
            decimal_places=7,
            default=None,
            blank=True,
            null=True
        ))
    ]
